language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7"
notifications:
  email: false
script: npm run coverage
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
